name: web

# Controls when the workflow will run
on:
  push:
    paths:
      - 'staticwebsite/**'

jobs:
  terraform:
    runs-on: ubuntu-latest

    name: 'web'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      WORKING_DIR: ./staticwebsite
      
    steps:
      - uses: actions/checkout@v4.1.1

      - name: 'Terraform init'
        id: init
        run: terraform init
        working-directory: ${{ env.WORKING_DIR }}

      - name: 'Terraform plan'
        id: plan
        run: terraform plan
        working-directory: ${{ env.WORKING_DIR }}
                    
      - name: 'Check last commit message'
        id: commit
        run: echo "MESSAGE=$(git log --format=%B -n 1)" >> $GITHUB_ENV

      - name: 'Conditionally run Terraform action'
        run: |
          if [[ "${{ env.MESSAGE }}" == *"destroy"* ]]; then
            terraform destroy -auto-approve -var="source_content=<h1>Web page created with terraform</h1>" -var="index_document=index.html"
          else
            terraform apply -auto-approve -var="source_content=<h1>Web page created with terraform</h1>" -var="index_document=index.html"
          fi
        working-directory: ${{ env.WORKING_DIR }}
